### ISSUE TITLE
Ajouter la Validation du Nom de Fichier dans saveToFile

### ISSUE THREAD

**Issue by rognit** [Weean257/GL02_DigitalDynasty#9]
Fichier calendar.js
Assurer la validation du nom de fichier dans saveToFile pour éviter les caractères non valides et potentiellement dangereux.

**Comment by hkrzn** [comment]
Ticket assigné à Hortense KERSUZAN - Closed : 
Pour ajouter la validation du nom de fichier dans la fonction saveToFile et éviter les caractères non valides ou potentiellement dangereux, on utilise une expression régulière pour vérifier que le nom de fichier est conforme à certaines règles. Dans cette correction, la variable validFilename est obtenue en remplaçant tous les caractères non valides par des underscores (_) à l'aide de l'expression régulière /[^a-zA-Z0-9._-]/g. Cela assure que le nom de fichier ne contient que des lettres, des chiffres, des points, des tirets et des underscores. Ensuite, le chemin du fichier est construit avec le nom de fichier validé.
